spring.profiles.default: integration-test
spring.config:
  import:
    - classpath:/application-rds.yml
    - classpath:/application-redis.yml
    - classpath:/application-mongo.yml
    - classpath:/application-external.yml


---
spring.config:
  activate:
    on-profile: integration-test

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /api

spring:
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
