secret:
  security:
    user:
      name: <SECURITY_NAME>
      password: <SECURITY_PW>


---
spring.config:
  activate:
    on-profile: <PROFILE>

secret:
  sentry:
    dsn: <SENTRY_DSN>
  jdbc:
    uri: <JDBC_URI>
    username: <JDBC_USERNAME>
    password: <JDBC_PASSWORD>
  aws:
    cloudfront:
      url: <CLOUDFRONT_URL>
  mongodb:
    url: <MONGO_DB>
  slack:
    token:
      boss-manager: <SLACK_TOKEN_BOSS_MANAGER>
      daily-statistics: <SLACK_TOKEN_DAILY_STATISTICS>
      monitoring: <SLACK_TOKEN_MONITORING>
  spring:
    redis:
      host: <REDIS_HOST>
      port: <REDIS_PORT>

