### 전체 가간동안 특정 사장님의 가게의 피드백을 조회합니다
GET {{host_boss_api}}/v1/boss/store/{{BOSS_STORE_ID}}/feedbacks/full

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}


### 특정 기간동안 특정 사장님의 가게의 피드백을 조회합니다
GET {{host_boss_api}}/v1/boss/store/{{BOSS_STORE_ID}}/feedbacks/specific?startDate=2022-02-12&endDate=2022-02-17

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}


### 사장님 가게 피드백의 타입 목록을 조회합니다.
GET {{host_boss_api}}/v1/boss/store/feedback/types

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}
