spring.profiles.default: local
spring.config:
  import:
    - classpath:/application-rds.yml
    - classpath:/application-redis.yml
    - classpath:/application-mongo.yml
    - classpath:/application-external.yml
    - classpath:/application-sentry.yml
    - classpath:/application-swagger.yml
    - classpath:/application-actuator.yml
    - optional:classpath:/application-secret.yml

threedollars:
  aplication:
    uid: ${random.uuid}

server:
  port: 5000
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /api
  tomcat:
    threads:
      max: 200
    connection-timeout: 10s
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2KB

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm
    servlet:
      load-on-startup: 1
    pathmatch:
      matching-strategy: ant_path_matcher

---
spring.config:
  activate:
    on-profile: dev

spring:
  datasource:
    primary:
      hikari:
        maximum-pool-size: 5
    secondary:
      hikari:
        maximum-pool-size: 5


---
spring.config:
  activate:
    on-profile:
      - prod
      - staging

spring:
  datasource:
    primary:
      hikari:
        maximum-pool-size: 5
    secondary:
      hikari:
        maximum-pool-size: 10


---
