version: "3"
services:
  api:
    build: .
    ports:
      - "5000:5000"
    command: java -jar threedollar-api.jar
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
  admin:
    build:
      context: .
      dockerfile: Dockerfile_admin
    ports:
      - "5100:5100"
    command: java -jar threedollar-admin.jar
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
  statistics:
    build:
      context: .
      dockerfile: Dockerfile_statistics
    ports:
      - "5200:5200"
    command: java -jar threedollar-statistics.jar
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
