### 사장님 계정의 디바이스 정보를 저장 및 갱신합니다
PUT {{boss-api}}/v1/device
Content-Type: application/json
Authorization: Bearer {{BOSS_AUTHORIZATION}}
User-Agent: 1.0.0 (com.macgongmon.-dollar-in-my-pocket-manager-dev; build:7; iOS 15.5.0)

{
    "pushToken": "cnkMARPadUBEvTli2d3CKi:APA91bEU_WMVJ-b_Wcw3yLpDENpV-HuFH2QcdMUMJjGfaRIpj_NtDl7wW-kCeoSz6BpRMW0tPNfZ7Ug8VJC3XOu3PexbnUVKoh6-j0dPA320-T6Ywd3KLi7URb624IiKrNeB8kngiqLt",
    "pushPlatformType": "FCM"
}

> {%
client.test("200 OK", () => {
    client.assert(response.status === 200, "응답 실패");
});
%}


### (IOS) 사장님 계정의 디바이스 정보를 저장 및 갱신합니다
PUT {{boss-api}}/v1/device
Content-Type: application/json
Authorization: Bearer {{BOSS_AUTHORIZATION}}
User-Agent: okhttp/4.9.1
X-ANDROID-SERVICE-VERSION: 1.0.0


{
    "pushToken": "cnkMARPadUBEvTli2d3CKi:APA91bEU_WMVJ-b_Wcw3yLpDENpV-HuFH2QcdMUMJjGfaRIpj_NtDl7wW-kCeoSz6BpRMW0tPNfZ7Ug8VJC3XOu3PexbnUVKoh6-j0dPA320-T6Ywd3KLi7URb624IiKrNeB8kngiqLt",
    "pushPlatformType": "FCM"
}

> {%
client.test("200 OK", () => {
    client.assert(response.status === 200, "응답 실패");
});
%}


### 사장님 계정의 디바이스 정보를 삭제합니다
DELETE {{boss-api}}/v1/device
Authorization: Bearer {{BOSS_AUTHORIZATION}}
User-Agent: 1.0.0 (com.macgongmon.-dollar-in-my-pocket-manager-dev; build:7; iOS 15.5.0)


> {%
client.test("200 OK", () => {
    client.assert(response.status === 200, "응답 실패");
});
%}
