### Health Check
GET {{host_boss_api}}/ping


### 테스트 토큰 발급
GET {{host_boss_api}}/test-token

> {%
client.global.set("BOSS_AUTHORIZATION", response.body["data"]["token"])
%}


### Add Mock Store data
POST {{host_boss_api}}/test-store?latitude=38&longitude=127&categoriesIds=61f29cdea82b8f1c21309259
Content-Type: application/json
Authorization: Bearer {{BOSS_AUTHORIZATION}}

> {%
client.global.set("BOSS_STORE_ID", response.body["id"])
%}


### Add Mock Store data
POST {{host_boss_api}}/test-category?title=중식&priority=1
