### Health Check
GET {{host_boss_api}}/ping


### 테스트 토큰 발급
GET {{host_boss_api}}/test-token

> {%
client.global.set("BOSS_AUTHORIZATION", response.body["data"]["token"])
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}


### Add Mock Store data
POST {{host_boss_api}}/test-store?latitude=38&longitude=127


### Add Mock Store data
POST {{host_boss_api}}/test-category?title=중식&priority=1
