spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        query.in_clause_parameter_padding: true
    open-in-view: false # OSIV off
  datasource:
    initialization-mode: never

---
spring.config:
  activate:
    on-profile: integration-test

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    primary:
      hikari:
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
    secondary:
      hikari:
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
  flyway:
    enabled: false


---
spring.config:
  activate:
    on-profile: local

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDB102Dialect
  datasource:
    primary:
      hikari:
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:threedollar;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
        username: sa
        password:
    secondary:
      hikari:
        driver-class-name: org.h2.Driver
        jdbc-url: jdbc:h2:mem:threedollar;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
        username: sa
        password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  flyway:
    enabled: false


---
spring.config:
  activate:
    on-profile: local-docker

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDB102Dialect
        connection.provider_disables_autocommit: true
  datasource:
    primary:
      hikari:
        auto-commit: false
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://localhost:3309/threedollar_test
        username: root
        password: 3dollar
    secondary:
      hikari:
        auto-commit: false
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://localhost:3309/threedollar_test
        username: root
        password: 3dollar
  flyway:
    enabled: true


---
spring.config:
  activate:
    on-profile:
      - dev
      - prod
      - stage

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB102Dialect
        connection.provider_disables_autocommit: true
  datasource:
    primary:
      hikari:
        auto-commit: false
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: ${secret.jdbc.uri}
        username: ${secret.jdbc.username}
        password: ${secret.jdbc.password}
    secondary:
      hikari:
        auto-commit: false
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: ${secret.jdbc.uri}
        username: ${secret.jdbc.username}
        password: ${secret.jdbc.password}
  flyway:
    enabled: true


---
