### 모든 FAQ를 조회합니다.
GET {{boss-api}}/v1/faqs

> {%
client.test("200 OK", () => {
    client.assert(response.status === 200, "응답 실패");
});
%}


### 특정 카테고리의 FAQ를 조회합니다.
GET {{boss-api}}/v1/faqs?category=ETC

> {%
client.test("200 OK", () => {
    client.assert(response.status === 200, "응답 실패");
});
%}


### 모든 FAQ 카테고리를 조회합니다.
GET {{boss-api}}/v1/faq/categories

> {%
client.test("200 OK", () => {
    client.assert(response.status === 200, "응답 실패");
});
%}
