spring.profiles.default: integration-test
spring.config:
  import:
    - classpath:/application-external.yml
    - classpath:/application-sqs.yml


---
spring.config:
  activate:
    on-profile: integration-test
