spring:
  config:
    import:
      - classpath:/application-domain.yml
      - classpath:/application-external.yml
      - classpath:/application-redis.yml
  profiles:
    active: integration-test


---
spring.config:
  activate:
    on-profile: integration-test

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /api

spring:
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
