spring.config:
  activate:
    on-profile: integration-test

spring:
  redis:
    host: localhost
    port: 9998
    timeout: 3000
  cache:
    type: none


---
spring.config:
  activate:
    on-profile: local

spring:
  redis:
    host: localhost
    port: 6379
    timeout: 3000


---
spring.config:
  activate:
    on-profile: local-docker

spring:
  redis:
    host: localhost
    port: 6380
    timeout: 3000


---
spring.config:
  activate:
    on-profile:
      - dev
      - prod
      - stage

spring:
  redis:
    host: ${secret.spring.redis.host}
    port: ${secret.spring.redis.port}
    timeout: 3000


---
