### 단건 푸시
POST {{push-api}}/test/push/message
Content-Type: application/json

{
    "token": "cnkMARPadUBEvTli2d3CKi:APA91bEU_WMVJ-b_Wcw3yLpDENpV-HuFH2QcdMUMJjGfaRIpj_NtDl7wW-kCeoSz6BpRMW0tPNfZ7Ug8VJC3XOu3PexbnUVKoh6-j0dPA320-T6Ywd3KLi7URb624IiKrNeB8kngiqLt",
    "title": "제목",
    "body": "내용"
}


### 다건 푸시
POST {{push-api}}/test/push/message/bulk
Content-Type: application/json

{
    "tokens": [
        "cnkMARPadUBEvTli2d3CKi:APA91bEU_WMVJ-b_Wcw3yLpDENpV-HuFH2QcdMUMJjGfaRIpj_NtDl7wW-kCeoSz6BpRMW0tPNfZ7Ug8VJC3XOu3PexbnUVKoh6-j0dPA320-T6Ywd3KLi7URb624IiKrNeB8kngiqLt",
        "cnkMARPadUBEvTli2d3CKi:APA91bEU_WMVJ-b_Wcw3yLpDENpV-HuFH2QcdMUMJjGfaRIpj_NtDl7wW-kCeoSz6BpRMW0tPNfZ7Ug8VJC3XOu3PexbnUVKoh6-j0dPA320-T6Ywd3KLi7URb624IiKrNeB8kngiqLt",
        "cnkMARPadUBEvTli2d3CKi:APA91bEU_WMVJ-b_Wcw3yLpDENpV-HuFH2QcdMUMJjGfaRIpj_NtDl7wW-kCeoSz6BpRMW0tPNfZ7Ug8VJC3XOu3PexbnUVKoh6-j0dPA320-T6Ywd3KLi7URb624IiKrNeB8kngiqLt"
    ],
    "title": "제목",
    "body": "내용"
}
