server:
  port: 5000
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  profiles:
    active: local
    include:
      - domain
      - auth
      - cloud
      - rds
      - redis
      - actuator
      - security
      - monitoring
      - sentry
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
