spring:
  config:
    activate:
      on-profile: local,local-will
  boot:
    admin:
      client:
        enabled: false
sentry:
  logging:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: dev
  boot:
    admin:
      client:
        enabled: false
        url: ${ADMIN_SERVER_URL}
        instance:
          name: threedollar-api
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
            tags:
              environment: dev
sentry:
  environment: dev
  traces-sample-rate: 0.05
  dsn: ${secret.sentry.dsn}
---
spring:
  config:
    activate:
      on-profile: prod
  boot:
    admin:
      client:
        enabled: false
sentry:
  environment: prod
  traces-sample-rate: 0.05
  dsn: ${secret.sentry.dsn}
---
