server:
  port: 5000
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  profiles:
    active: local
    default: local
    include:
      - domain
      - cloud
      - rds
      - redis
      - actuator
      - security
      - monitoring
      - sentry
      - slack
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000
        loggerLevel: FULL
