secret:
  apple:
    client_id:
    issuer:
  security:
    user:
      name:
      password:
  sentry:
    dsn:
  slack:
    token:
  jdbc:
    uri:
    username:
    password:
spring:
  config:
    activate:
      on-profile:
