management:
  endpoints:
    web:
      base-path: /monitoring
      exposure:
        include:
          - health
          - sessions
          - metrics
          - threaddump
          - heapdump
          - loggers
          - logfile
          - scheduledtasks
          - configprops
  endpoint:
    health:
      show-details: always
