spring:
  boot:
    admin:
      client:
        url: admin
        instance:
          name: threedollar-api
          metadata:
            user:
              name: ${spring.security.user.name}
              password: ${spring.security.user.password}
            tags:
              environment: dev
  config:
    activate:
      on-profile: dev
---
spring:
  boot:
    admin:
      client:
        enabled: false
  config:
    activate:
      on-profile: local,local-will,prod
