spring:
  config:
    activate:
      on-profile: local,local-will
sentry:
  logging:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: dev
sentry:
  environment: dev
  traces-sample-rate: 0.05
  dsn: ${secret.sentry.dsn}
---
spring:
  config:
    activate:
      on-profile: prod
sentry:
  environment: prod
  traces-sample-rate: 0.05
  dsn: ${secret.sentry.dsn}
---
