server:
  port: 8080
spring:
  profiles:
    active: local
    include:
      - domain
      - jwt
      - auth
      - cloud
      - credential
      - swagger
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
