server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
spring:
  profiles:
    active: local
    include:
      - domain
      - jwt
      - auth
      - cloud
      - credential
      - agent
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    log-request-details: true
logging:
  file:
    path: logs/api/
