server:
  port: 5000
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  profiles:
    active: local
    default: local
    include:
      - domain
      - cloud
      - redis
      - actuator
      - sentry
      - thirdparty
      - feign
      - security
      - secret
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
