server:
  port: 5001
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  profiles:
    active: local
    default: local
    include:
      - elasticsearch
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
