### 사장님 계정 가입 신청을 승인합니다.
PUT {{host_admin}}/v1/registration/{{REGISTRATION_ID}}/apply
Authorization: Bearer {{ADMIN_AUTHORIZATION}}

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}


### 사장님 계정 가입 신청을 반려합니다.
PUT {{host_admin}}/v1/registration/{{REGISTRATION_ID}}/reject
Authorization: Bearer {{ADMIN_AUTHORIZATION}}

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}
