version: "3.9"
services:
  api:
    image: ${API_IMAGE}:${TAG}
    ports:
      - 5001:5000
    deploy:
      replicas: 2
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    links:
      - "redis:redis"
    volumes:
      - ~/logs:/logs
    env_file:
      - ~/env/dev.env
  redis:
    image: redis
    command: redis-server --port 6379
    volumes:
      - ~/db/data:/data
