version: "3.9"
services:
  api:
    image: ${API_IMAGE}:${TAG}
    ports:
      - "5001:5000"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
      - "NEW_RELIC_APP_NAME=3dollars-api-dev"
    links:
      - "redis:redis"
      - "elasticsearch:elasticsearch"
    volumes:
      - ~/logs:/logs
    env_file:
      - ~/env/dev.env
    stop_signal: SIGTERM
    stop_grace_period: 1m
    restart: unless-stopped
  redis:
    image: redis
    command: redis-server --port 6379
    volumes:
      - ~/db/data:/data
  elasticsearch:
    image: elasticsearch:7.16.2
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped
    environment:
      - "discovery.type=single-node"
    volumes:
      - ~/threedollars-api/elasticsearch:/usr/share/elasticsearch/data
