version: "3.9"
services:
  api:
    image: ${API_IMAGE}:${TAG}
    ports:
      - "5001:5000"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    links:
      - "redis:redis"
    volumes:
      - ~/logs:/logs
    env_file:
      - ~/env/dev.env
    stop_signal: SIGTERM
    stop_grace_period: 1m
    restart: unless-stopped
  redis:
    image: redis
    command: redis-server --port 6379
    volumes:
      - ~/db/data:/data
