package com.depromeet.threedollar.domain.mongo.domain.bossservice.feedback

import com.depromeet.threedollar.domain.mongo.domain.bossservice.feedback.repository.BossStoreFeedbackRepositoryCustom
import com.depromeet.threedollar.domain.mongo.domain.bossservice.feedback.repository.statistics.BossStoreFeedbackStatisticsRepositoryCustom
import org.springframework.data.mongodb.repository.MongoRepository

interface BossStoreFeedbackRepository : MongoRepository<BossStoreFeedback, String>, BossStoreFeedbackRepositoryCustom, BossStoreFeedbackStatisticsRepositoryCustom
