spring.config:
  activate:
    on-profile: integration-test

spring:
  redis:
    host: localhost
    port: 9998
    timeout: 3000
    connect-timeout: 3000
  cache:
    type: none

---
spring.config:
  activate:
    on-profile: local

spring:
  redis:
    host: localhost
    port: 6379
    timeout: 3000
    connect-timeout: 3000


---
spring.config:
  activate:
    on-profile: local-docker

spring:
  redis:
    host: localhost
    port: 6380
    timeout: 3000
    connect-timeout: 3000


---
spring.config:
  activate:
    on-profile: dev

spring:
  redis:
    host: threedollar-dev-redis.xbz0jn.0001.apn2.cache.amazonaws.com
    port: 6379
    timeout: 3000
    connect-timeout: 3000


---
spring.config:
  activate:
    on-profile:
      - prod
      - stage

spring:
  redis:
    host: threedollar-api-redis-prod.tqy2kj.0001.apn2.cache.amazonaws.com
    port: 6379
    timeout: 3000
    connect-timeout: 3000


---
