### 사장님 계정의 회원가입을 요청합니다.
POST {{boss-api}}/v1/auth/signup
Content-Type: application/json

{
    "token": "token",
    "bossName": "토깽이",
    "socialType": "KAKAO",
    "businessNumber": "000-00-00000",
    "storeName": "가슴속 3천원",
    "storeCategoriesIds": [
        "{{BOSS_CATEGORY_ID}}"
    ],
    "contactsNumber": "010-1234-1234",
    "certificationPhotoUrl": "https://www.jungle.co.kr/image/9184139c4725921ad8526df7"
}

> {%
client.global.set("BOSS_AUTHORIZATION", response.body["data"]["token"])
client.global.set("REGISTRATION_ID", response.body["data"]["bossId"])
client.test("200 OK", () => {
    client.assert(response.status === 200, "응답 실패");
});
%}


### 사장님 계정의 로그인을 요청합니다.
POST {{boss-api}}/v1/auth/login
Content-Type: application/json

{
    "token": "token",
    "socialType": "KAKAO"
}

> {%
client.global.set("BOSS_AUTHORIZATION", response.body["data"]["token"])
client.global.set("REGISTRATION_ID", response.body["data"]["bossId"])
client.test("200 OK", () => {
    client.assert(response.status === 200, "응답 실패");
});
%}


### 사장님 계정을 로그아웃을 요청합니다.
POST {{boss-api}}/v1/auth/logout
Content-Type: application/json
Authorization: Bearer {{BOSS_AUTHORIZATION}}

> {%
client.test("200 OK", () => {
    client.assert(response.status === 200, "응답 실패");
});
%}


### 사장님 계정의 회원탈퇴를 요청합니다.
DELETE {{boss-api}}/v1/auth/signout
Content-Type: application/json
Authorization: Bearer {{BOSS_AUTHORIZATION}}

> {%
client.test("200 OK", () => {
    client.assert(response.status === 200, "응답 실패");
});
%}
