### 광고를 저장합니다.
POST {{host_admin}}/v1/user/advertisement
Authorization: Bearer {{ADMIN_AUTHORIZATION}}
Content-Type: application/json

{
    "position": "SPLASH",
    "platform": "ALL",
    "imageUrl": "https://image.png",
    "linkUrl": "https://link.com",
    "title": "광고 제목",
    "subTitle": "광고 내용\n광고 내용을 입력해주세요",
    "bgColor": "#ffffff",
    "fontColor": "#2e2e2e",
    "startDateTime": "2023-01-01T00:00:00",
    "endDateTime": "2024-01-01T00:00:00"
}

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}


### 전체 광고 목록을 조회합니다.
GET {{host_admin}}/v1/user/advertisements?page=1&size=3
Authorization: Bearer {{ADMIN_AUTHORIZATION}}

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}


### 특정 광고 정보를 수정합니다
PUT {{host_admin}}/v1/user/advertisement/1
Authorization: Bearer {{ADMIN_AUTHORIZATION}}
Content-Type: application/json

{
    "position": "SPLASH",
    "platform": "AOS",
    "imageUrl": "https://image1.png",
    "linkUrl": "https://link1.com",
    "title": "광고 제목",
    "subTitle": "광고 내용\n광고 내용을 입력해주세요",
    "bgColor": "#ffffff",
    "fontColor": "#2e2e2e",
    "startDateTime": "2023-01-01T00:00:00",
    "endDateTime": "2023-03-01T00:00:00"
}

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}


### 특정 광고를 삭제한다
DELETE {{host_admin}}/v1/user/advertisement/1
Authorization: Bearer {{ADMIN_AUTHORIZATION}}

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}
