spring:
  config:
    import: classpath:/application-domain.yml
  profiles:
    active: integration-test
    default: integration-test


---
spring:
  config:
    activate:
      on-profile: integration-test
