### Health Check API
GET {{vendor_api}}/ping

> {%
client.test("200 OK", () => {
    client.assert(response.status === 200, "응답 실패");
});
%}


### (개발 서버용) 테스트를 위한 세션
GET {{vendor_api}}/test-token

> {%
client.global.set("AUTHORIZATION", response.body["data"]["token"])
client.test("200 OK", () => {
    client.assert(response.status === 200, "응답 실패");
});
%}
