server:
  port: 4000
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /boss
  tomcat:
    threads:
      max: 200
    connection-timeout: 5s

spring:
  profiles:
    active: local
    default: local
    include:
      - domain
      - redis
      - mongo
      - external
      - swagger
      - secret

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm
    servlet:
      load-on-startup: 1

---
spring.config:
  activate:
    on-profile: dev

spring:
  datasource:
    hikari:
      maximum-pool-size: 10


---
spring.config:
  activate:
    on-profile:
      - prod
      - stage

spring:
  datasource:
    hikari:
      maximum-pool-size: 10


---
