server:
  port: 4000
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  profiles:
    active: local
    default: local
    include:
      - domain
      - redis
      - mongo
      - secret
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm:ss
