package com.depromeet.threedollar.domain.mongo.domain.bossservice.registration

import com.depromeet.threedollar.domain.mongo.domain.bossservice.registration.repository.BossRegistrationRepositoryCustom
import com.depromeet.threedollar.domain.mongo.domain.bossservice.registration.repository.statistics.BossRegistrationStatisticsRepositoryCustom
import org.springframework.data.mongodb.repository.MongoRepository

interface BossRegistrationRepository : MongoRepository<BossRegistration, String>, BossRegistrationRepositoryCustom, BossRegistrationStatisticsRepositoryCustom
