cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

---
spring.config:
  activate:
    on-profile:
      - local
      - local-docker
      - integration-test

cloud:
  aws:
    s3:
      bucket: dummy-s3-bucket
    cloudfront:
      url: dummy-cloudfront


---
spring.config:
  activate:
    on-profile:
      - dev
      - prod
      - staging

cloud:
  aws:
    s3:
      bucket: ${secret.aws.s3.bucket}
    cloudfront:
      url: ${secret.aws.cloudfront.url}
    credentials:
      instance-profile: true


---
