spring:
  security:
    user:
      name: ${secret.security.user.name}
      password: ${secret.security.user.password}

management:
  endpoints:
    web:
      base-path: /monitoring
      exposure:
        include:
          - health
          - flyway
          - metrics
          - circuitbreakers
          - circuitbreakerevents
  endpoint:
    health:
      show-details: always


---
spring.config:
  activate:
    on-profile:
      - local
      - local-docker
      - staging

sentry:
  logging:
    enabled: false


---
spring.config:
  activate:
    on-profile:
      - dev

sentry:
  environment: dev
  traces-sample-rate: 0.05
  dsn: ${secret.sentry.dsn}


---
spring.config:
  activate:
    on-profile:
      - prod

sentry:
  environment: prod
  traces-sample-rate: 0.05
  dsn: ${secret.sentry.dsn}


---
