spring:
  profiles: local
  redis:
    host: localhost
    port: 6379
---
spring:
  profiles: dev
  redis:
    host: redis
    port: 6379
---
spring:
  profiles: prod
  redis:
    host: threedollar-redis-session.tqy2kj.ng.0001.apn2.cache.amazonaws.com
    port: 6379
