spring:
  profiles:
    active: local
    default: local
    include:
      - domain
      - secret
      - external
      - dummy
  batch:
    job:
      names: ${job.name:NONE}
  main:
    web-application-type: none

logging:
  level:
    org.springframework.batch: DEBUG
