apple:
  client_id: dummy-client-id
cloud:
  aws:
    s3:
      bucket: dummy-s3-bucket
    cloudfront:
      url: dummy-cloudfront
    region:
      static: ap-northeast-2
    stack:
      auto: false
