spring:
  profiles:
    active: local
    default: local
    include:
      - domain
      - secret
      - feign
      - logging
      - dummy
  batch:
    job:
      names: ${job.name:NONE}
  main:
    web-application-type: none
