spring.profiles.default: local
spring.config:
  import:
    - classpath:/application-rds.yml
    - classpath:/application-mongo.yml
    - classpath:/application-external.yml
    - classpath:/application-sqs.yml
    - optional:classpath:/application-secret.yml
    - optional:classpath:/application-dummy.yml

spring:
  application:
    name: 3dollars-in-my-pocket-batch
  batch:
    job:
      names: ${job.name:NONE}
  main:
    web-application-type: none
