cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC

external:
  client:
    kakao:
      profile:
        base-url: https://kapi.kakao.com
        url: /v2/user/me
    google:
      profile:
        base-url: https://www.googleapis.com
        url: /oauth2/v2/userinfo
    apple:
      profile:
        base-url: https://appleid.apple.com
        url: /auth/keys
    naver:
      profile:
        base-url: https://openapi.naver.com
        url: /v1/nid/me
    slack:
      webhook:
        base-url: https://hooks.slack.com/services

---
spring.config:
  activate:
    on-profile:
      - local
      - local-docker
      - integration-test

cloud:
  aws:
    s3:
      bucket: dummy-s3-bucket
    cloudfront:
      url: dummy-cloudfront

apple:
  client_id: dummy-apple-client-id
  issuer: dummy-apple-issue

slack:
  token:
    daily-statistics: dummy-token
    monitoring: dummy-token
    boss-manager: dummy-token


---
spring.config:
  activate:
    on-profile: dev

cloud:
  aws:
    s3:
      bucket: 3dollar-api-bucket-dev
    cloudfront:
      url: ${secret.aws.cloudfront.url}
    credentials:
      instance-profile: true

apple:
  client_id: ${secret.apple.client_id}
  issuer: https://appleid.apple.com

slack:
  token:
    daily-statistics: ${secret.slack.token.daily-statistics}
    monitoring: ${secret.slack.token.monitoring}
    boss-manager: ${secret.slack.token.boss-manager}


---
spring.config:
  activate:
    on-profile:
      - prod
      - staging

cloud:
  aws:
    s3:
      bucket: 3dollar-api-bucket-prod
    cloudfront:
      url: ${secret.aws.cloudfront.url}
    credentials:
      instance-profile: true

apple:
  client_id: ${secret.apple.client_id}
  issuer: https://appleid.apple.com

slack:
  token:
    daily-statistics: ${secret.slack.token.daily-statistics}
    monitoring: ${secret.slack.token.monitoring}
    boss-manager: ${secret.slack.token.boss-manager}


---
