logging:
  level:
    com.amazonaws.util.EC2MetadataUtils: error
    com.amazonaws.internal.InstanceMetadataServiceResourceFetcher: error
---
cloud:
  aws:
    s3:
      bucket: 3dollar-local-embedded-bucket
    cloudfront:
      url: http://localhost:10000/${cloud.aws.s3.bucket}/
    region:
      static: ap-northeast-2
    stack:
      auto: false
spring:
  config:
    activate:
      on-profile:
        - local
        - local-will
---
cloud:
  aws:
    s3:
      bucket: 3dollar-api-bucket
    cloudfront:
      url: ${secret.aws.cloudfront.url}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: true
spring:
  config:
    activate:
      on-profile: dev
---
cloud:
  aws:
    s3:
      bucket: 3dollar-api-bucket-prod
    cloudfront:
      url: ${secret.aws.cloudfront.url}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instance-profile: true
spring:
  config:
    activate:
      on-profile: prod
