version: '3.8'

services:
  mariadb-master:
    container_name: 3dollars-in-my-pocket-mariadb-master
    image: docker.io/bitnami/mariadb:10.4
    ports:
      - '3310:3306'
    volumes:
      - mariadb-volume:/bitnami/mariadb
    restart: unless-stopped
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_USER=threedollar
      - MARIADB_DATABASE=threedollar_test
      - MARIADB_ROOT_PASSWORD=threedollar
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6
    networks:
      - threedollar-network

  mariadb-slave:
    container_name: 3dollars-in-my-pocket-mariadb-slave
    image: docker.io/bitnami/mariadb:10.4
    ports:
      - '3311:3306'
    depends_on:
      - mariadb-master
    restart: unless-stopped
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      - MARIADB_USER=threedollar
      - MARIADB_DATABASE=threedollar_test
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=threedollar
      - ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ 'CMD', '/opt/bitnami/scripts/mariadb/healthcheck.sh' ]
      interval: 15s
      timeout: 5s
      retries: 6
    networks:
      - threedollar-network

  redis:
    image: redis:6.0
    container_name: 3dollars-in-my-pocket-redis
    command: redis-server --port 6379
    ports:
      - '6380:6379'
    restart: unless-stopped
    volumes:
      - cache-volume:/data
    networks:
      - threedollar-network
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 15s
      timeout: 5s
      retries: 6

  mongodb:
    image: mongo:5.0
    container_name: 3dollars-in-my-pocket-mongodb
    ports:
      - '27018:27017'
    restart: unless-stopped
    volumes:
      - mongodb-volume:/data/db
    networks:
      - threedollar-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 15s
      timeout: 5s
      retries: 6

volumes:
  mariadb-volume:
    driver: local
  mongodb-volume:
    driver: local
  cache-volume:
    driver: local

networks:
  threedollar-network:
