### 특정 거리 안에 위치한 사장님 가게 목록을 조회합니다. (거리순)
GET {{host_api}}/v1/boss/stores/around?mapLatitude=38&mapLongitude=127.01&distanceKm=1&latitude=38.0&longitude=127.2&orderType=DISTANCE_ASC

> {%
client.test("200 OK", function() {
    client.global.set("BOSS_STORE_ID", response.body["data"][0]["bossStoreId"])
    client.assert(response.status === 200, "응답 실패");
});
%}


### 특정 거리 안에 위치한 사장님 가게 목록을 조회합니다. (스티커 순)
GET {{host_api}}/v1/boss/stores/around?mapLatitude=38&mapLongitude=127.01&distanceKm=1&latitude=38.0&longitude=127.2&orderType=TOTAL_FEEDBACKS_COUNTS_DESC

> {%
client.test("200 OK", function() {
    client.global.set("BOSS_STORE_ID", response.body["data"][0]["bossStoreId"])
    client.assert(response.status === 200, "응답 실패");
});
%}


### 특정 사장님 가게의 정보를 상세 조회합니다
GET {{host_api}}/v1/boss/store/{{BOSS_STORE_ID}}?latitude=38.0&longitude=127.1

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}

