server:
  port: 5100
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  profiles:
    active: local
    default: local
    include:
      - domain
      - redis
