server:
  port: 4000
  servlet:
    encoding:
      charset: UTF-8
spring:
  profiles:
    active: local
    include:
      - domain
      - jwt
  mvc:
    log-request-details: true
logging:
  file:
    path: logs/admin/
