server:
  port: 4000
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
spring:
  profiles:
    active: local
    include:
      - domain
      - jwt
      - security
