spring.config:
  activate:
    on-profile: integration-test

spring:
  data:
    mongodb:
      host: localhost
      port: 0
      database: test
  mongodb:
    embedded:
      version: 3.2.8


---
spring.config:
  activate:
    on-profile: local

spring:
  data:
    mongodb:
      host: localhost
      port: 0
      database: test
  mongodb:
    embedded:
      version: 3.2.8


---
spring.config:
  activate:
    on-profile: local-docker

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: threedollar


---
spring.config:
  activate:
    on-profile: dev

spring:
  data:
    mongodb:
      uri: ${secret.mongodb.uri}


---
