spring.config:
  activate:
    on-profile:
      - integration-test
      - local

spring:
  data:
    mongodb:
      host: localhost
      port: 0
      database: test

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG


---
spring.config:
  activate:
    on-profile: local-docker

spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: threedollar

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG


---
spring.config:
  activate:
    on-profile:
      - dev
      - stage
      - prod

spring:
  data:
    mongodb:
      uri: ${secret.mongodb.uri}


---
