spring:
  data:
    mongodb:
      host: localhost
      port: 0
      database: test
  config:
    activate:
      on-profile: local
---
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: threedollar
  config:
    activate:
      on-profile: local-docker
---
