spring.config:
  activate:
    on-profile:
      - integration-test
      - local

spring:
  data:
    mongodb:
      uri: mongodb://localhost:${random.int(49152,65535)}/test?connectTimeoutMS=5000&maxPoolSize=10&minPoolSize=10


---
spring.config:
  activate:
    on-profile: local-docker

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27018/threedollar?connectTimeoutMS=5000&maxPoolSize=10&minPoolSize=10


---
spring.config:
  activate:
    on-profile:
      - dev
      - staging
      - prod

spring:
  data:
    mongodb:
      uri: ${secret.mongodb.uri}


---
