spring.config:
  activate:
    on-profile:
      - integration-test
      - local

spring:
  data:
    mongodb:
      host: localhost
      port: 0
      database: test


---
spring.config:
  activate:
    on-profile: local-docker

spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: threedollar


---
spring.config:
  activate:
    on-profile:
      - dev
      - staging
      - prod

spring:
  data:
    mongodb:
      uri: ${secret.mongodb.uri}


---
