### (Deprecated) 특정 가게의 정보를 조회합니다. (v2.0)
GET {{host_api}}/api/v2/store/?storeId={{STORE_ID}}&latitude=34&longitude=126

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}


### (Deprecated) [인증] 사용자가 작성한 가게의 정보를 조회합니다. (첫 스크롤)
GET {{host_api}}/api/v2/stores/me?size=10
Authorization: {{AUTHORIZATION}}

> {%
client.test("200 OK", function() {
    client.global.set("CURSOR", response.body["data"]["nextCursor"])
    client.assert(response.status === 200, "응답 실패");
});
%}


### (Deprecated) 거리순으로 특정 카테고리의 가게 정보를 조회합니다.
GET {{host_api}}/api/v2/stores/distance?size=5&page=0&latitude=34&longitude=126&mapLatitude=34&mapLongitude=126&category=BUNGEOPPANG

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}


### (Deprecated) 리뷰순으로 특정 카테고리의 가게 정보를 조회합니다.
GET {{host_api}}/api/v2/stores/review?size=5&page=0&latitude=34&longitude=126&mapLatitude=34&mapLongitude=126&category=BUNGEOPPANG

> {%
client.test("200 OK", function() {
    client.assert(response.status === 200, "응답 실패");
});
%}
