cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false

push:
  sqs:
    boss:
      single-push: ${secret.push.sqs.boss.single-push}
      bulk-push: ${secret.push.sqs.boss.bulk-push}


---
spring.config:
  activate:
    on-profile:
      - local-docker

push:
  sqs:
    boss:
      single-push: threedollars-boss-single-push-sqs
      bulk-push: threedollars-boss-bulk-push-sqs


cloud:
  aws:
    credentials:
      access-key: threedollars
      secret-key: threedollars
    end-point:
      uri: http://localhost:4566


---
spring.config:
  activate:
    on-profile:
      - local
      - integration-test

push:
  sqs:
    boss:
      single-push: local-boss-single-push
      bulk-push: local-boss-bulk-push


---
