threedollars.aplication.uid: ${random.uuid}

server:
  port: 5000
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /api
  tomcat:
    threads:
      max: 200
    connection-timeout: 30s

spring:
  profiles:
    active: local
    default: local
    include:
      - rds
      - redis
      - mongo
      - sentry
      - external
      - swagger
      - actuator
      - secret

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm
    servlet:
      load-on-startup: 1

---
spring.config:
  activate:
    on-profile: dev

spring:
  datasource:
    primary:
      hikari:
        maximum-pool-size: 5
    secondary:
      hikari:
        maximum-pool-size: 5

---
spring.config:
  activate:
    on-profile:
      - prod
      - stage

spring:
  datasource:
    primary:
      hikari:
        maximum-pool-size: 5
    secondary:
      hikari:
        maximum-pool-size: 10


---
