secret:
  apple:
    client_id: <APPLE_CLIENT_ID>
  security:
    user:
      name: <SECURITY_NAME>
      password: <SECURITY_PW>
---
secret:
  sentry:
    dsn: <SENTRY_DSN>
  slack:
    token: <SLACK_TOKEN>
  jdbc:
    uri: <JDBC_URI>
    username: <JDBC_USERNAME>
    password: <JDBC_PASSWORD>
  aws:
    cloudfront:
      url: <CLOUDFRONT_URL>
spring:
  config:
    activate:
      on-profile: <PROFILE>
