server:
  port: 5000
  shutdown: graceful
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: /api
  tomcat:
    threads:
      max: 200
    connection-timeout: 30s

spring:
  profiles:
    active: local
    default: local
    include:
      - rds
      - redis
      - sentry
      - external
      - swagger
      - secret

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd'T'HH:mm:ss
      time: HH:mm
    servlet:
      load-on-startup: 1

  security:
    user:
      name: ${secret.security.user.name}
      password: ${secret.security.user.password}

management:
  endpoints:
    web:
      base-path: /monitoring
      exposure:
        include:
          - health
          - metrics
          - threaddump
          - heapdump
          - loggers
          - configprops
  endpoint:
    health:
      show-details: always
    logfile:
      external-file: /logs/threedollar-api-user/info.log

---
spring.config:
  activate:
    on-profile: dev

spring:
  datasource:
    hikari:
      maximum-pool-size: 10


---
spring.config:
  activate:
    on-profile:
      - prod
      - stage

spring:
  datasource:
    hikari:
      maximum-pool-size: 20


---
