### 메달을 추가한다
POST {{host_admin}}/v1/medal
Authorization: Bearer {{ADMIN_AUTHORIZATION}}
Content-Type: application/json

{
    "name": "메달 이름",
    "introduction": "메달 소개",
    "activationIconUrl": "https://activation.png",
    "disableIconUrl": "https://disable.png",
    "conditionType": "ADD_REVIEW",
    "conditionCount": 3,
    "acquisitionDescription": "획득 조건 설명"
}


### 특정 메달을 수정한다
PUT {{host_admin}}/v1/medal/1
Authorization: Bearer {{ADMIN_AUTHORIZATION}}
Content-Type: application/json

{
    "name": "변경된 메달 이름",
    "introduction": "변경된 메달 소개",
    "activationIconUrl": "https://changed-activation.png",
    "disableIconUrl": "https://changed-disable.png"
}
