### 테스트를 위한 세션
GET {{user-api}}/test-token

> {%
client.global.set("AUTHORIZATION", response.body["data"]["token"])
%}


### 회원가입
POST {{user-api}}/v2/signup
Content-Type: application/json
Authorization: {{AUTHORIZATION}}

{
    "token": "token",
    "name": "가슴속 3천원",
    "socialType": "KAKAO"
}


### 로그인
POST {{user-api}}/v2/login
Content-Type: application/json
Authorization: {{AUTHORIZATION}}

{
    "token": "token",
    "socialType": "KAKAO"
}


### [인증] 회원탈퇴를 요청합니다
DELETE {{user-api}}/v2/signout
Authorization: {{AUTHORIZATION}}

> {%
client.test("200 OK", () => {
    client.assert(response.status === 200, "응답 실패");
});
%}


### 테스트를 위한 세션
GET {{user-api}}/test-token

> {%
client.global.set("AUTHORIZATION", response.body["data"]["token"])
%}


### [인증] 로그아웃
POST {{user-api}}/v2/logout
Content-Type: application/json
Authorization: {{AUTHORIZATION}}

> {%
client.test("200 OK", () => {
    client.assert(response.status === 200, "응답 실패");
});
%}
