name: 운영 환경 - 유저 API 서버 Health Check (Common)

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: 광고 API - 메인 카드 (AOS)
        uses: jtalk/url-health-check-action@v2
        with:
          url: ${{ secrets.USER_API_BASE_URI }}/v1/advertisements?platform=AOS&position=MAIN_PAGE_CARD
          max-attempts: 3
          retry-delay: 3s

      - name: 광고 API - 메뉴 카테고리 배너 (AOS)
        uses: jtalk/url-health-check-action@v2
        with:
          url: ${{ secrets.USER_API_BASE_URI }}/v1/advertisements?platform=AOS&position=MENU_CATEGORY_BANNER
          max-attempts: 3
          retry-delay: 3s

      - name: 광고 API - 스플래시 (AOS)
        uses: jtalk/url-health-check-action@v2
        with:
          url: ${{ secrets.USER_API_BASE_URI }}/v1/advertisements?platform=AOS&position=SPLASH
          max-attempts: 3
          retry-delay: 3s

      - name: 광고 API - (AOS)
        uses: jtalk/url-health-check-action@v2
        with:
          url: ${{ secrets.USER_API_BASE_URI }}/v1/advertisements?platform=AOS&position=STORE_CATEGORY_LIST
          max-attempts: 3
          retry-delay: 3s

      - name: 광고 API (IOS)
        uses: jtalk/url-health-check-action@v2
        with:
          url: ${{ secrets.USER_API_BASE_URI }}/v1/advertisements?platform=IOS&position=MAIN_PAGE_CARD
          max-attempts: 3
          retry-delay: 3s

      - name: 광고 API (IOS)
        uses: jtalk/url-health-check-action@v2
        with:
          url: ${{ secrets.USER_API_BASE_URI }}/v1/advertisements?platform=IOS&position=MENU_CATEGORY_BANNER
          max-attempts: 3
          retry-delay: 3s

      - name: 광고 API (IOS)
        uses: jtalk/url-health-check-action@v2
        with:
          url: ${{ secrets.USER_API_BASE_URI }}/v1/advertisements?platform=IOS&position=SPLASH
          max-attempts: 3
          retry-delay: 3s

      - name: 광고 API (IOS)
        uses: jtalk/url-health-check-action@v2
        with:
          url: ${{ secrets.USER_API_BASE_URI }}/v1/advertisements?platform=IOS&position=STORE_CATEGORY_LIST
          max-attempts: 3
          retry-delay: 3s

      - name: FAQ API
        uses: jtalk/url-health-check-action@v2
        with:
          url: ${{ secrets.USER_API_BASE_URI }}/v2/faqs
          max-attempts: 3
          retry-delay: 3s

      - name: Medal API
        uses: jtalk/url-health-check-action@v2
        with:
          url: ${{ secrets.USER_API_BASE_URI }}/v1/medals
          max-attempts: 3
          retry-delay: 3s

      - name: action-slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow
          custom_payload: |
            {
              attachments: [{
                color: 'danger',
                text: `${process.env.AS_WORKFLOW}\n유저 API의 캐시 API가 실패하였습니다`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
