### 사장님 계정의 회원가입을 요청합니다.
POST {{host_boss_api}}/v1/auth/signup
Content-Type: application/json

{
    "token": "UFzZUqHtCpEAr_OiLAnbkcseCFkfLpNdNxmiWwopyWAAAAF_ee0t4Q",
    "bossName": "토깽이",
    "socialType": "KAKAO",
    "businessNumber": "123-45-12341",
    "storeName": "가슴속 3천원",
    "storeCategoriesIds": [
        "{{BOSS_CATEGORY_ID}}"
    ],
    "contactsNumber": "010-1234-1234",
    "certificationPhotoUrl": "https://www.jungle.co.kr/image/9184139c4725921ad8526df7"
}

> {%
client.global.set("REGISTRATION_ID", response.body["data"]["registrationId"])
%}


### 사장님 계정의 회원탈퇴를 요청합니다.
DELETE {{host_boss_api}}/v1/auth/sign-out
Content-Type: application/json
Authorization: Bearer {{BOSS_AUTHORIZATION}}

